### ISSUE TITLE
@Before methods in batch integration tests are called after job completion

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seed#1]
Due to the nature of the batch integration testing (triggered with @WithCommandLine), the requested job execution completes before the call to @Before. 

The @Before method should be called after kernel initialization but before the job execution. I'm not sure if its possible but this should be investigated. Maybe some hooks in the test initialization process could do the job.

**Comment by ejemba** [comment]
Why not provide a custom annotation with the good behaviour in that case.
@CliBefore or something else.
