### ISSUE TITLE
Move to the latest version of Sisu-Guice

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seed#125]
Upgrade Nuun and Seed to the latest sisu-guice (currently the 3.2.6).

**Comment by pith** [comment]
I tested an upgrade to the latest sisu-guice. It seems that we won't be able to migrate right now as Shiro is not compatible with Guice 4. Otherwise everything seems to be working in Nuun and Seed.

See the releated open [JIRA](https://issues.apache.org/jira/browse/SHIRO-493)

**Comment by adrienlauer** [comment]
Mmm. Crap. Any ideas about what is incompatible ? Nothing we can fix ourselves ?

**Comment by pith** [comment]
This is explained by James Moger comment in the JIRA. This is due to a change in the Key constructor. The shiro guice integration used to subclass Key which no more works.

> In Guice 4 you are no longer able to subclass Key with a generic type and have that be the final class in the graph.

**Comment by ydautremay** [comment]
Oh dang ! Will there be a new version of shiro/guice to solve this ?

**Comment by pith** [comment]
Well the issue was reported in April 2014 and it's still not fixed. So I don't see any solution coming. We might have to fix it on our own.

@ydautremay we can discuss it on IRC if you have any idea :wink:

**Comment by adrienlauer** [comment]
Finally we moved to official Guice 4.0, see #196
