### ISSUE TITLE
Improve reusability of SeedReflectionUtils

### ISSUE THREAD

**Issue by pith** [seedstack/seed#13]
This class is widely used in SeedStack, but there is often one method by use case. It should be a very good idea to refactor this class.

https://github.com/seedstack/seed/blob/master/core-support/core/src/main/java/org/seedstack/seed/core/utils/SeedReflectionUtils.java#L36

**Comment by adrienlauer** [comment]
SeedReflectionUtils is gone in 3.0.0, replaced by more versatile utilities in seedstack/shed.
