### ISSUE TITLE
Duplicated code in SeedReflectionUtils

### ISSUE THREAD

**Issue by pith** [seedstack/seed#143]
This whole method ([SeedReflectionUtils](https://github.com/seedstack/seed/blob/a2c45981bd318597f4f64335c5e1e389092c09ea/core/src/main/java/org/seedstack/seed/core/utils/SeedReflectionUtils.java#L189-L213)) is duplicated here ([BaseClassSpecifications](https://github.com/seedstack/seed/blob/a2c45981bd318597f4f64335c5e1e389092c09ea/core/src/main/java/org/seedstack/seed/core/utils/BaseClassSpecifications.java#L376-L406)).

I don't know which one should be removed.

**Comment by adrienlauer** [comment]
SeedReflectionsUtils is gone in 3.0.0, replaced by more versatile utilities in seedstack/shed.
