### ISSUE TITLE
Problem with JPA Transaction & JMS

### ISSUE THREAD

**Issue by tbouvet** [seedstack/seed#148]
It's not possible to have a JPA transaction inside a JmsListener.

For example:
``` java
@JmsMessageListener(connection = "connection-1", destinationTypeStr = "QUEUE", destinationName = "${queue1.name}")
public class MessageReceiver implements MessageListener {
	@Transactional
	@JpaUnit("xxx")
	void createPayload(String payloadMessage) throws Exception {
                repository.save(....)
	}
```
In this case, the JPA transaction is overrided by the JMS transaction, and an exception is thrown
```
org.seedstack.seed.core.api.SeedException: (JPA) Accessing entity manager outside transaction

Description
-----------
No active transaction when accessing JPA EntityManager.
```

The problem seems to be in the [class](https://github.com/seedstack/jms-addon/blob/master/core/src/main/java/org/seedstack/seed/jms/internal/JmsTransactionMetadataResolver.java#L27-L33) below. If the class is a MessageListener, the transaction handler is a JMS handler.
``` java
public class JmsTransactionMetadataResolver implements TransactionMetadataResolver {
    @Override
    public TransactionMetadata resolve(MethodInvocation methodInvocation, TransactionMetadata defaults) {
        Class<?> declaringClass = methodInvocation.getMethod().getDeclaringClass();
        if (MessageListener.class.isAssignableFrom(declaringClass)) {
            TransactionMetadata transactionMetadata = new TransactionMetadata();
            transactionMetadata.setHandler(JmsListenerTransactionHandler.class);
            transactionMetadata.setResource(declaringClass.getCanonicalName());

            return transactionMetadata;
```

**Comment by adrienlauer** [comment]
The transaction model is method-based. In this case you effectively have two transactions on the same method. The implicit JMS transaction and the explicit JPA transaction.

To do this you must isolate the JPA transaction is another method of the listener. In that case, due to AOP limitations, the method must have the protected or package visbility.

**Comment by tbouvet** [comment]
Linked to seedstack/jms-addon#3
