### ISSUE TITLE
Merge Args with CliArgs

### ISSUE THREAD

**Issue by pith** [seedstack/seed#152]
The classes in `org.seedstack.seed.spi.command` and `org.seedstack.seed.cli` packages might not be used in the same context but they still are the same concepts.

Moreover it seems that they don't have exactly the same implementation, so take the best of both. We might also look the JCommander project for inspiration.

**Comment by adrienlauer** [comment]
They both rely on commons-cli now but further merging would require a significant breaking change. Not willing to do this.
