### ISSUE TITLE
Why not scan all the JAX-RS providers ?

### ISSUE THREAD

**Issue by pith** [seedstack/seed#168]
Currently the REST plugin only scans some types of providers. I don't know why.

```java
BaseClassSpecifications.or(
                classAnnotatedWith(Provider.class).and(classImplements(MessageBodyWriter.class)),
                classAnnotatedWith(Provider.class).and(classImplements(ContextResolver.class)),
                classAnnotatedWith(Provider.class).and(classImplements(MessageBodyReader.class)),
                classAnnotatedWith(Provider.class).and(classImplements(ExceptionMapper.class))
        ).isSatisfiedBy(candidate)
```

https://github.com/seedstack/seed/blob/bfe6de606802445c9cc82d5199f41c5f9f79b478/rest/core/src/main/java/org/seedstack/seed/rest/internal/JaxRsProviderSpecification.java#L29-L33

**Comment by adrienlauer** [comment]
I always thought those providers were the only four defined in the spec. At least the 1.0 spec. But i never verified it myself. Time to check.

**Comment by ejemba** [comment]
@adrienlauer is right at time when I wrote this piece of code only 4 type of providers were specified in 1.0 Spec.

**Comment by adrienlauer** [comment]
The specification to detect providers was updated in #172
