### ISSUE TITLE
New configuration system

### ISSUE THREAD

**Issue by pith** [seedstack/seed#187]
The configuration should be POJO oriented.

The new system should handle multiple providers:
- Multiple file formats (yaml, json)
- Environment variables
- Java system properties
- Command line 
- Etcd, Consul, Zookeeper, etc.
- legacy (with props and common configuration)

Features:
- Override
- Hot reload (with change listener)
- Documentation (with search)
- Debugging (effective properties)
- Alias
- Validation (ConfigurationException)

Bonus: study the possibility to have converters in order to help the migration to newer formats.

**Comment by ydautremay** [comment]
This looks apetizing :+1:

**Comment by pith** [comment]
@ydautremay happy to see that you liked it ! See you on IRC ;)

**Comment by ejemba** [comment]
That's cool ! 
Perhaps zookeeper can be added to the list at least for the conception phase.
Etcd and consul provide listeners each with their own technologies.

**Comment by pith** [comment]
Yes this system will provide an SPI for configuration providers. So any source could be added.

**Comment by tbouvet** [comment]
I like zookeeper too !
For Etcd and Consul, I test the 2 (in a docker environment for the service discovery).

**Comment by pith** [comment]
By the way we want this project to be a library independent from Seed. 
@seedstack/backend @seedstack/friends do you have any idea for a name ?

**Comment by ydautremay** [comment]
-SuperConfig
-AwesomeConfig
-PowerConf
-BetterConfiguration
-PropertiesSuck
-TweakMyApp

**Comment by ejemba** [comment]
@ydautremay no recursive acronym this time ;) ;)
* Yet Another Config
* ZeeConf 
* FonK → FunK → FonkY → FunkY
* FunkyConf

**Comment by pith** [comment]
Guys, what about "Coffig": coffee + config ? (Thanks @kavi87 for the idea)

**Comment by ejemba** [comment]
@pith sure this is funny AND it is relevant as well !

**Comment by pith** [comment]
We created the repo, see seedstack/coffig

**Comment by adrienlauer** [comment]
New configuration system is enabled in seed 3.0.0. Hot reloading and effective configuration are still thingsd to do but specific issues should be opened when requested.

**Comment by ejemba** [comment]
@adrienlauer what do you mean by "effective configuration" ?

**Comment by adrienlauer** [comment]
This was mentionned in the initial post by @pith (effective properties). This means a dump of the real gathered configuration (including remote sources) in a global tree. Like a Maven effective pom.
