### ISSUE TITLE
Provide a wrapper for Guice Injector

### ISSUE THREAD

**Issue by pith** [seedstack/seed#22]
We usually use the Guice injector directly in our support. It would be a good idea to provide a wrapper which will allow to **inject a specific interface** instead of allowing the injection of any bounded interface. This will also limit the usage of Guice classes in the stack. The objective being that only the modules and maybe the plugins will be adherent to Guice classes.

**Possible API:**

``` java
@Inject
SeedProvider<MyInterface> myInterfaceProvider;

...

MyInterface myInterface = myInterfaceProvider.get();

MyInterface myInterface = myInterfaceProvider.get("my-qualifier");
```

**Comment by adrienlauer** [comment]
[Injecting providers](https://github.com/google/guice/wiki/InjectingProviders) is possible natively with Guice and the business framework provides a registries to retrieve an particular implementation dynamically. This is not a necessary feature at the moment.
