### ISSUE TITLE
Remove Dependencies from business-specs to seed-core.

### ISSUE THREAD

**Issue by ejemba** [seedstack/seed#220]
We have a direct dependency from business-specs to seed-core. 
The item linked are SeedException and Seed Core Specifications.
This is in term of layering a little glitch because we can not use the specs of the business without pulling seed core. What I need right now. 

can we : 
- put the exception engine inside it's own module ?
- put the Specifications inside seed-specs ? 

What do you think ?

As we imagine the business specs as a technology free java pure module to ease DDD having dependency one core may not be advised.

**Comment by adrienlauer** [comment]
Done by only keeping interfaces and annotations in specs module. Base classes and other support classes have been moved to core (no package change).

**Comment by ejemba** [comment]
@adrienlauer many many thanks !!!!! you're the best 👍 
I'll review this :)
