### ISSUE TITLE
Websocket endpoints not being parsed by Guice

### ISSUE THREAD

**Issue by Sherpard** [seedstack/seed#243]
Websockets are not taking into account guice injection.

Building a websocket with Constructor injection would result in a crash due Servlet not being able to find a public constructor with 0 parameters.

Building a websocket with FieldInjection would run, but Injection would not be performed. thus being unable to interact with the stack

I've prepared a test project that suffers the issue
https://github.com/Sherpard/SeedGuiceWebsocketFailureExample

It's a project build with archetype + websocket implementation present on the documentation http://seedstack.org/docs/web/websockets/

**Comment by Sherpard** [comment]
Found out what was happening.

Since 18.4, @ServerEndpoint requires a configurator. pretty much like @ClientEndpoint
If a configurator is not present, Websocket-api falls back to its [default value](https://javaee.github.io/javaee-spec/javadocs/javax/websocket/server/ServerEndpoint.html#configurator--), 
 [ServerEndpointConfig.Configurator](https://javaee.github.io/javaee-spec/javadocs/javax/websocket/server/ServerEndpointConfig.Configurator.html)

It would be nice to add a hint to this behavior to the official documentation

**Comment by Sherpard** [comment]
Updated documentation in PR https://github.com/seedstack/website/pull/74

**Comment by adrienlauer** [comment]
The PR has been merged, closing this issue.
