### ISSUE TITLE
Is slowEquals still needed?

### ISSUE THREAD

**Issue by Sherpard** [seedstack/seed#256]
I'm currently digging trough security-related code, and I've been reading quite a bit

I stumbled upon [ByteArrays.java](https://github.com/seedstack/seed/blob/master/core/src/main/java/org/seedstack/seed/core/internal/crypto/ByteArrays.java) class

I understand that it was needed prior to [Java6u17](https://www.oracle.com/technetwork/java/javase/6u17-141447.html) as there was a timing attack vector, that was fixed.
Now that stack requires at least Java 8, we may drop such utility in flavor of native [MessageDigest.isEqual ](https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html#isEqual-byte:A-byte:A-)

If we find out that we no longer need ByteArrays, I can take care of building a pull request.

**Comment by adrienlauer** [comment]
Agree ! Thank you for the PR.
