### ISSUE TITLE
Configuration - Class Arrays are ignored by Coffig

### ISSUE THREAD

**Issue by Sherpard** [seedstack/seed#281]
Coffig allows a plethora of ways to configure the software. But, fails when trying to map a Class<>[] , Instead of the values, it is assigned with an empty array.

I've somewhat followed the execution path to Coffig code, 

I was unable to reproduce the bug using Coffig alone, so I've added a test case at Seed-core as an example of how to reproduce the error.

**Comment by adrienlauer** [comment]
Fixed by #286
