### ISSUE TITLE
Support javax.transaction.Transactional in the transaction support

### ISSUE THREAD

**Issue by pith** [seedstack/seed#29]
Our transaction support is based on the `org.seedstack.seed.transaction.api.Transactional`. But as the `javax.transaction.Transactional` annotation is pull by hibernate, our users using hibernate have both annotations in their classpath. If someone chose the wrong annotation it won't work and the error can be difficult to find.
A solution whould be to support the `javax.transaction.Transactional` in the `MetadataResolver`.

**Comment by adrienlauer** [comment]
Note that we would need to upgrade to JTA 1.2 for this to work. We may have a problem if a class (I think of MetadataResolver) references a JTA 1.2 class (@Transactional) a must still be used in a JTA 1.1 application. Some reflections tricks may be needed.

**Comment by adrienlauer** [comment]
Done while maintaining JTA 1.1 compatibility (although not sure if really needed).
