### ISSUE TITLE
Data import: differentiate mock/golden data

### ISSUE THREAD

**Issue by pith** [seedstack/seed#38]
Today SEED core provides a feature to import data at startup. But it doesn't differentiate golden data required for production and mocks that are only used for production.

To change we should add another imported directory:
- `META-INF/data` for golden data (already exists)
- `META-INF/mock` for mocks

By default if a mock is present in the `mock` directory, it will override the data in the `data` directory.
The framework should allow to override this behavior by a property. It might be useful to override the behavior only for a given group of data.

**Comment by adrienlauer** [comment]
META-INF/data can be used in test classpath to complement golden data. I think the case for replacing golden data is not solid as golden data are part of the application and should be present in tests
