### ISSUE TITLE
@Transactional doesn't work on interface methods

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seed#52]
Applying the Transactional annotation on interface methods (like a finder interface method) doesn't trigger the transaction interceptor. It seems that the matcher (based on SeedReflectionUtils.*) doesn't recognize them. Them same matching strategy is adequately used for detecting REST methods in some cases, so if a refactoring must be done, both cases (REST + transactions) must be considered.

**Comment by pith** [comment]
Closed as duplicate #74
