### ISSUE TITLE
Bug in C3p0DataSourceProvider

### ISSUE THREAD

**Issue by mariaantonia** [seedstack/seed#68]
There is a bug when initializing the C3p0DataSourceProvider. In the method provide, the user and password are set incorrectly:
            cpds.setUser(url);
            cpds.setPassword(user);

The link to the code: https://github.com/seedstack/seed/blob/9fe187817e374cf464c07fd219b548c269626ccf/persistence-support/jdbc/src/main/java/org/seedstack/seed/persistence/jdbc/internal/datasource/C3p0DataSourceProvider.java#L42-L43

**Comment by adrienlauer** [comment]
Thank you for your report @mariaantonia !
As you can see the bug was fixed in the latest snapshot, which will be released on 28th of July.
