### ISSUE TITLE
Unify annotation scanning

### ISSUE THREAD

**Issue by pith** [seedstack/seed#74]
Some of the methods used to scan annotations are centralized in `SeedReflectionUtils` (which needs a deep refactoring) but I occurs that others leaked into the code. Moreover the behavior differs between those methods, some check annotations on:
- implementation, 
- implementation and parent class,
- implementation, parent class and parent methods.

Non exhaustive list of feature using it:
- Security (`@RequiresRoles`, `@RequiresPermissions`),
- Transaction (`@Transactional`, `@JpaUnit`, ...),
- Business (`@Finder`, `@ApplicationService`, ...),
- DataSecurity (`@Secured`)

This should be fixed with a unique method `findAnnotation(Method method)`. If some use cases require a different method, the behavior of this method should be documented both in the code and the manual.

**Comment by adrienlauer** [comment]
SeedReflectionUtils is gone in 3.0.0, replace by more versatile utilities in seedstack/shed. More specifically annotation scanning has been unified through the StandardAnnotationResolver base class in shed. It is used anywhere we need to search an annotation on a method/constructor or a class.
