### ISSUE TITLE
Resource classes are not managed by Jersey

### ISSUE THREAD

**Issue by pith** [seedstack/seed#95]
For now it seems that the `@Path` annotation is mandatory on the resource class. This is not the case in the JAX-RS spec.

I checked the specification used by the REST plugin and it is OK. So I don't know where the problem comes from.

**Comment by adrienlauer** [comment]
Classes with method-only `@Path` annotation don't qualify as JAX-RS root resources so shouldn't be detected and bound by Seed. The specification used to detected those root resources has been updated in 029568cfbe4d683c6eaa6a4d6e9a537552b36d84.
